

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class TextBox;
                ref class TextBlock;
                ref class ListView;
                ref class AppBarButton;
            }
        }
    }
}

namespace Wp81Wol
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::StackPanel^ PanelListComputerItem;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ PanelEditComputerItem;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ PanelHelp;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBoxName;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBoxMacAddress;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ListViewIsEmpty;
        private: ::Windows::UI::Xaml::Controls::ListView^ ListViewComputerItem;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ AddAppBarButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ SaveAppBarButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ DeleteAppBarButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ HelpAppBarButton;
    };
}

